blogger_admin:
    resource: "@BloggerAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

blogger_blog:
   resource: "@BloggerBlogBundle/Resources/config/routing.yml"
   prefix:   /

#app:
 #   resource: "@AppBundle/Controller/"
  #  type:     annotation
