#blogger_blog_homepage:
 #   path:     /
  #  defaults: { _controller: BloggerBlogBundle:Default:index }
#blogger_blog_list:
 #   path: /blog
  #  defaults: { _controller: BloggerBlogBundle:Blog:list }

#blogger_blog_show:
 #   path: /blog/show/{id}
  #  defaults: { _controller: BloggerBlogBundle:Blog:show }
blogger_blog_list:
    path: /
    defaults: { _controller: BloggerBlogBundle:Blog:list }

blogger_blog_show:
    path: /show/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }

blogger_blog_contact:
    path:  /contact
    defaults: { _controller: BloggerBlogBundle:Blog:contact }
blogger_comment_create:
    path:  /comment/{post_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method: POST
        post_id: \d+


